Add k8s manifests and dev tooling
mattermost/matterbuild pull request #37
Opened 2020-06-17 20:19 UTC by khos2ow

#### Summary

Adding Kubernetes manifests and all the required developer toolings to be used on workstations.

#### Ticket Link

2020-06-19 17:16 UTC, metanerd requested changes
It is beautiful! So convenient, I really like it!

2020-06-19 17:16 UTC, metanerd commented on README.md
> +
I guess it is missing kustomize?

2020-06-19 17:16 UTC, metanerd commented on README.md
> +
Please add `config.json` to the readme.

2020-06-19 17:31 UTC, khos2ow commented on README.md
> +
done

2020-06-22 15:51 UTC, metanerd approved these changes
Nice!

2020-06-22 15:59 UTC, merged